[package]
name = "imgtool"
version = "0.1.0"
edition = "2024"
description = "A simple cli tool to compress and convert images based on libcaesium."

[dependencies]
imagesize = "0.14.0"
libcaesium = "0.17.4"
structopt = "0.3.26"
